// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ApolloWrapper from "@/lib/apollo/apollo-wrapper";
import Header from "./components/navbar/Header";
import localFont from "next/font/local";

const blippo = localFont({
  src: "/fonts/blippo-blk-bt.ttf",
  variable: "--font-blippo",
  display: "swap",
});

const baumans = localFont({
  src: "/fonts/Baumans-Regular.ttf",
  variable: "--font-baumans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${blippo.variable} ${baumans.variable} antialiased`}>
        <ApolloWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={true}
          >
            <Header />
            <main>{children}</main>
          </ThemeProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
