export interface Country {
  name: string;
  slug: string;
  active: boolean;
  currencyCode: string;
  currencySymbol: string;
  languageCode: string;
}

export const countries: Country[] = [
  {
    name: "India",
    slug: "in",
    active: true,
    currencyCode: "INR",
    currencySymbol: "₹",
    languageCode: "en-IN",
  },
  {
    name: "Australia",
    slug: "au",
    active: true,
    currencyCode: "AUD",
    currencySymbol: "$",
    languageCode: "en-AU",
  },
  /* { name: "Afghanistan", slug: "af", active: false, currencyCode: "AFN", currencySymbol: "؋" },
  { name: "Åland Islands", slug: "ax", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Albania", slug: "al", active: false, currencyCode: "ALL", currencySymbol: "L" },
  { name: "Algeria", slug: "dz", active: false, currencyCode: "DZD", currencySymbol: "د.ج" },
  { name: "Andorra", slug: "ad", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Angola", slug: "ao", active: false, currencyCode: "AOA", currencySymbol: "Kz" },
  { name: "Anguilla", slug: "ai", active: false, currencyCode: "XCD", currencySymbol: "$" },
  { name: "Antigua & Barbuda", slug: "ag", active: false, currencyCode: "XCD", currencySymbol: "$" },
  { name: "Argentina", slug: "ar", active: false, currencyCode: "ARS", currencySymbol: "$" },
  { name: "Armenia", slug: "am", active: false, currencyCode: "AMD", currencySymbol: "֏" },
  { name: "Aruba", slug: "aw", active: false, currencyCode: "AWG", currencySymbol: "ƒ" },
  { name: "Ascension Island", slug: "ac", active: false, currencyCode: "SHP", currencySymbol: "£" },
  { name: "Austria", slug: "at", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Azerbaijan", slug: "az", active: false, currencyCode: "AZN", currencySymbol: "₼" },
  { name: "Bahamas", slug: "bs", active: false, currencyCode: "BSD", currencySymbol: "$" },
  { name: "Bahrain", slug: "bh", active: false, currencyCode: "BHD", currencySymbol: ".د.ب" },
  { name: "Bangladesh", slug: "bd", active: false, currencyCode: "BDT", currencySymbol: "৳" },
  { name: "Barbados", slug: "bb", active: false, currencyCode: "BBD", currencySymbol: "$" },
  { name: "Belarus", slug: "by", active: false, currencyCode: "BYN", currencySymbol: "Br" },
  { name: "Belgium", slug: "be", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Belize", slug: "bz", active: false, currencyCode: "BZD", currencySymbol: "$" },
  { name: "Benin", slug: "bj", active: false, currencyCode: "XOF", currencySymbol: "CFA" },
  { name: "Bermuda", slug: "bm", active: false, currencyCode: "BMD", currencySymbol: "$" },
  { name: "Bhutan", slug: "bt", active: false, currencyCode: "BTN", currencySymbol: "Nu." },
  { name: "Bolivia", slug: "bo", active: false, currencyCode: "BOB", currencySymbol: "Bs." },
  { name: "Bosnia & Herzegovina", slug: "ba", active: false, currencyCode: "BAM", currencySymbol: "KM" },
  { name: "Botswana", slug: "bw", active: false, currencyCode: "BWP", currencySymbol: "P" },
  { name: "Bouvet Island", slug: "bv", active: false, currencyCode: "NOK", currencySymbol: "kr" },
  { name: "Brazil", slug: "br", active: false, currencyCode: "BRL", currencySymbol: "R$" },
  { name: "British Indian Ocean Territory", slug: "io", active: false, currencyCode: "USD", currencySymbol: "$" },
  { name: "British Virgin Islands", slug: "vg", active: false, currencyCode: "USD", currencySymbol: "$" },
  { name: "Brunei", slug: "bn", active: false, currencyCode: "BND", currencySymbol: "$" },
  { name: "Bulgaria", slug: "bg", active: false, currencyCode: "BGN", currencySymbol: "лв" },
  { name: "Burkina Faso", slug: "bf", active: false, currencyCode: "XOF", currencySymbol: "CFA" },
  { name: "Burundi", slug: "bi", active: false, currencyCode: "BIF", currencySymbol: "FBu" },
  { name: "Cambodia", slug: "kh", active: false, currencyCode: "KHR", currencySymbol: "៛" },
  { name: "Cameroon", slug: "cm", active: false, currencyCode: "XAF", currencySymbol: "CFA" },
  { name: "Canada", slug: "ca", active: false, currencyCode: "CAD", currencySymbol: "$" },
  { name: "Cape Verde", slug: "cv", active: false, currencyCode: "CVE", currencySymbol: "$" },
  { name: "Caribbean Netherlands", slug: "bq", active: false, currencyCode: "USD", currencySymbol: "$" },
  { name: "Cayman Islands", slug: "ky", active: false, currencyCode: "KYD", currencySymbol: "$" },
  { name: "Central African Republic", slug: "cf", active: false, currencyCode: "XAF", currencySymbol: "CFA" },
  { name: "Chad", slug: "td", active: false, currencyCode: "XAF", currencySymbol: "CFA" },
  { name: "Chile", slug: "cl", active: false, currencyCode: "CLP", currencySymbol: "$" },
  { name: "China", slug: "cn", active: false, currencyCode: "CNY", currencySymbol: "¥" },
  { name: "Christmas Island", slug: "cx", active: false, currencyCode: "AUD", currencySymbol: "$" },
  { name: "Cocos (Keeling) Islands", slug: "cc", active: false, currencyCode: "AUD", currencySymbol: "$" },
  { name: "Colombia", slug: "co", active: false, currencyCode: "COP", currencySymbol: "$" },
  { name: "Comoros", slug: "km", active: false, currencyCode: "KMF", currencySymbol: "CF" },
  { name: "Congo - Brazzaville", slug: "cg", active: false, currencyCode: "XAF", currencySymbol: "CFA" },
  { name: "Congo - Kinshasa", slug: "cd", active: false, currencyCode: "CDF", currencySymbol: "FC" },
  { name: "Cook Islands", slug: "ck", active: false, currencyCode: "NZD", currencySymbol: "$" },
  { name: "Costa Rica", slug: "cr", active: false, currencyCode: "CRC", currencySymbol: "₡" },
  { name: "Côte d’Ivoire", slug: "ci", active: false, currencyCode: "XOF", currencySymbol: "CFA" },
  { name: "Croatia", slug: "hr", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Cuba", slug: "cu", active: false, currencyCode: "CUP", currencySymbol: "$" },
  { name: "Curaçao", slug: "cw", active: false, currencyCode: "ANG", currencySymbol: "ƒ" },
  { name: "Cyprus", slug: "cy", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Czechia", slug: "cz", active: false, currencyCode: "CZK", currencySymbol: "Kč" },
  { name: "Denmark", slug: "dk", active: false, currencyCode: "DKK", currencySymbol: "kr" },
  { name: "Djibouti", slug: "dj", active: false, currencyCode: "DJF", currencySymbol: "Fdj" },
  { name: "Dominica", slug: "dm", active: false, currencyCode: "XCD", currencySymbol: "$" },
  { name: "Dominican Republic", slug: "do", active: false, currencyCode: "DOP", currencySymbol: "$" },
  { name: "Ecuador", slug: "ec", active: false, currencyCode: "USD", currencySymbol: "$" },
  { name: "Egypt", slug: "eg", active: false, currencyCode: "EGP", currencySymbol: "£" },
  { name: "El Salvador", slug: "sv", active: false, currencyCode: "USD", currencySymbol: "$" },
  { name: "Equatorial Guinea", slug: "gq", active: false, currencyCode: "XAF", currencySymbol: "CFA" },
  { name: "Eritrea", slug: "er", active: false, currencyCode: "ERN", currencySymbol: "Nfk" },
  { name: "Estonia", slug: "ee", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Eswatini", slug: "sz", active: false, currencyCode: "SZL", currencySymbol: "E" },
  { name: "Ethiopia", slug: "et", active: false, currencyCode: "ETB", currencySymbol: "Br" },
  { name: "Falkland Islands", slug: "fk", active: false, currencyCode: "FKP", currencySymbol: "£" },
  { name: "Faroe Islands", slug: "fo", active: false, currencyCode: "DKK", currencySymbol: "kr" },
  { name: "Fiji", slug: "fj", active: false, currencyCode: "FJD", currencySymbol: "$" },
  { name: "Finland", slug: "fi", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "France", slug: "fr", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "French Guiana", slug: "gf", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "French Polynesia", slug: "pf", active: false, currencyCode: "XPF", currencySymbol: "₣" },
  { name: "French Southern Territories", slug: "tf", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Gabon", slug: "ga", active: false, currencyCode: "XAF", currencySymbol: "CFA" },
  { name: "Gambia", slug: "gm", active: false, currencyCode: "GMD", currencySymbol: "D" },
  { name: "Georgia", slug: "ge", active: false, currencyCode: "GEL", currencySymbol: "₾" },
  { name: "Germany", slug: "de", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Ghana", slug: "gh", active: false, currencyCode: "GHS", currencySymbol: "₵" },
  { name: "Gibraltar", slug: "gi", active: false, currencyCode: "GIP", currencySymbol: "£" },
  { name: "Greece", slug: "gr", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Greenland", slug: "gl", active: false, currencyCode: "DKK", currencySymbol: "kr" },
  { name: "Grenada", slug: "gd", active: false, currencyCode: "XCD", currencySymbol: "$" },
  { name: "Guadeloupe", slug: "gp", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Guatemala", slug: "gt", active: false, currencyCode: "GTQ", currencySymbol: "Q" },
  { name: "Guernsey", slug: "gg", active: false, currencyCode: "GBP", currencySymbol: "£" },
  { name: "Guinea", slug: "gn", active: false, currencyCode: "GNF", currencySymbol: "FG" },
  { name: "Guinea-Bissau", slug: "gw", active: false, currencyCode: "XOF", currencySymbol: "CFA" },
  { name: "Guyana", slug: "gy", active: false, currencyCode: "GYD", currencySymbol: "$" },
  { name: "Haiti", slug: "ht", active: false, currencyCode: "HTG", currencySymbol: "G" },
  { name: "Heard & McDonald Islands", slug: "hm", active: false, currencyCode: "AUD", currencySymbol: "$" },
  { name: "Honduras", slug: "hn", active: false, currencyCode: "HNL", currencySymbol: "L" },
  { name: "Hong Kong SAR", slug: "hk", active: false, currencyCode: "HKD", currencySymbol: "$" },
  { name: "Hungary", slug: "hu", active: false, currencyCode: "HUF", currencySymbol: "Ft" },
  { name: "Iceland", slug: "is", active: false, currencyCode: "ISK", currencySymbol: "kr" },
  { name: "Indonesia", slug: "id", active: false, currencyCode: "IDR", currencySymbol: "Rp" },
  { name: "Iran", slug: "ir", active: false, currencyCode: "IRR", currencySymbol: "﷼" },
  { name: "Iraq", slug: "iq", active: false, currencyCode: "IQD", currencySymbol: "ع.د" },
  { name: "Ireland", slug: "ie", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Isle of Man", slug: "im", active: false, currencyCode: "GBP", currencySymbol: "£" },
  { name: "Israel", slug: "il", active: false, currencyCode: "ILS", currencySymbol: "₪" },
  { name: "Italy", slug: "it", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Jamaica", slug: "jm", active: false, currencyCode: "JMD", currencySymbol: "$" },
  { name: "Japan", slug: "jp", active: false, currencyCode: "JPY", currencySymbol: "¥" },
  { name: "Jersey", slug: "je", active: false, currencyCode: "GBP", currencySymbol: "£" },
  { name: "Jordan", slug: "jo", active: false, currencyCode: "JOD", currencySymbol: "د.ا" },
  { name: "Kazakhstan", slug: "kz", active: false, currencyCode: "KZT", currencySymbol: "₸" },
  { name: "Kenya", slug: "ke", active: false, currencyCode: "KES", currencySymbol: "KSh" },
  { name: "Kiribati", slug: "ki", active: false, currencyCode: "AUD", currencySymbol: "$" },
  { name: "Kosovo", slug: "xk", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Kuwait", slug: "kw", active: false, currencyCode: "KWD", currencySymbol: "د.ك" },
  { name: "Kyrgyzstan", slug: "kg", active: false, currencyCode: "KGS", currencySymbol: "с" },
  { name: "Laos", slug: "la", active: false, currencyCode: "LAK", currencySymbol: "₭" },
  { name: "Latvia", slug: "lv", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Lebanon", slug: "lb", active: false, currencyCode: "LBP", currencySymbol: "ل.ل" },
  { name: "Lesotho", slug: "ls", active: false, currencyCode: "LSL", currencySymbol: "L" },
  { name: "Liberia", slug: "lr", active: false, currencyCode: "LRD", currencySymbol: "$" },
  { name: "Libya", slug: "ly", active: false, currencyCode: "LYD", currencySymbol: "ل.د" },
  { name: "Liechtenstein", slug: "li", active: false, currencyCode: "CHF", currencySymbol: "CHF" },
  { name: "Lithuania", slug: "lt", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Luxembourg", slug: "lu", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Macao SAR", slug: "mo", active: false, currencyCode: "MOP", currencySymbol: "MOP$" },
  { name: "Madagascar", slug: "mg", active: false, currencyCode: "MGA", currencySymbol: "Ar" },
  { name: "Malawi", slug: "mw", active: false, currencyCode: "MWK", currencySymbol: "MK" },
  { name: "Malaysia", slug: "my", active: false, currencyCode: "MYR", currencySymbol: "RM" },
  { name: "Maldives", slug: "mv", active: false, currencyCode: "MVR", currencySymbol: "Rf" },
  { name: "Mali", slug: "ml", active: false, currencyCode: "XOF", currencySymbol: "CFA" },
  { name: "Malta", slug: "mt", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Martinique", slug: "mq", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Mauritania", slug: "mr", active: false, currencyCode: "MRU", currencySymbol: "UM" },
  { name: "Mauritius", slug: "mu", active: false, currencyCode: "MUR", currencySymbol: "₨" },
  { name: "Mayotte", slug: "yt", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Mexico", slug: "mx", active: false, currencyCode: "MXN", currencySymbol: "$" },
  { name: "Moldova", slug: "md", active: false, currencyCode: "MDL", currencySymbol: "L" },
  { name: "Monaco", slug: "mc", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Mongolia", slug: "mn", active: false, currencyCode: "MNT", currencySymbol: "₮" },
  { name: "Montenegro", slug: "me", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Montserrat", slug: "ms", active: false, currencyCode: "XCD", currencySymbol: "$" },
  { name: "Morocco", slug: "ma", active: false, currencyCode: "MAD", currencySymbol: "د.م." },
  { name: "Mozambique", slug: "mz", active: false, currencyCode: "MZN", currencySymbol: "MT" },
  { name: "Myanmar (Burma)", slug: "mm", active: false, currencyCode: "MMK", currencySymbol: "K" },
  { name: "Namibia", slug: "na", active: false, currencyCode: "NAD", currencySymbol: "$" },
  { name: "Nauru", slug: "nr", active: false, currencyCode: "AUD", currencySymbol: "$" },
  { name: "Nepal", slug: "np", active: false, currencyCode: "NPR", currencySymbol: "₨" },
  { name: "Netherlands", slug: "nl", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Netherlands Antilles", slug: "an", active: false, currencyCode: "ANG", currencySymbol: "ƒ" },
  { name: "New Caledonia", slug: "nc", active: false, currencyCode: "XPF", currencySymbol: "₣" },
  { name: "New Zealand", slug: "nz", active: false, currencyCode: "NZD", currencySymbol: "$" },
  { name: "Nicaragua", slug: "ni", active: false, currencyCode: "NIO", currencySymbol: "C$" },
  { name: "Niger", slug: "ne", active: false, currencyCode: "XOF", currencySymbol: "CFA" },
  { name: "Nigeria", slug: "ng", active: false, currencyCode: "NGN", currencySymbol: "₦" },
  { name: "Niue", slug: "nu", active: false, currencyCode: "NZD", currencySymbol: "$" },
  { name: "Norfolk Island", slug: "nf", active: false, currencyCode: "AUD", currencySymbol: "$" },
  { name: "North Korea", slug: "kp", active: false, currencyCode: "KPW", currencySymbol: "₩" },
  { name: "North Macedonia", slug: "mk", active: false, currencyCode: "MKD", currencySymbol: "ден" },
  { name: "Norway", slug: "no", active: false, currencyCode: "NOK", currencySymbol: "kr" },
  { name: "Oman", slug: "om", active: false, currencyCode: "OMR", currencySymbol: "ر.ع." },
  { name: "Pakistan", slug: "pk", active: false, currencyCode: "PKR", currencySymbol: "₨" },
  { name: "Palestinian Territories", slug: "ps", active: false, currencyCode: "ILS", currencySymbol: "₪" },
  { name: "Panama", slug: "pa", active: false, currencyCode: "PAB", currencySymbol: "B/." },
  { name: "Papua New Guinea", slug: "pg", active: false, currencyCode: "PGK", currencySymbol: "K" },
  { name: "Paraguay", slug: "py", active: false, currencyCode: "PYG", currencySymbol: "₲" },
  { name: "Peru", slug: "pe", active: false, currencyCode: "PEN", currencySymbol: "S/" },
  { name: "Philippines", slug: "ph", active: false, currencyCode: "PHP", currencySymbol: "₱" },
  { name: "Pitcairn Islands", slug: "pn", active: false, currencyCode: "NZD", currencySymbol: "$" },
  { name: "Poland", slug: "pl", active: false, currencyCode: "PLN", currencySymbol: "zł" },
  { name: "Portugal", slug: "pt", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Qatar", slug: "qa", active: false, currencyCode: "QAR", currencySymbol: "ر.ق" },
  { name: "Réunion", slug: "re", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Romania", slug: "ro", active: false, currencyCode: "RON", currencySymbol: "lei" },
  { name: "Russia", slug: "ru", active: false, currencyCode: "RUB", currencySymbol: "₽" },
  { name: "Rwanda", slug: "rw", active: false, currencyCode: "RWF", currencySymbol: "FRw" },
  { name: "Samoa", slug: "ws", active: false, currencyCode: "WST", currencySymbol: "T" },
  { name: "San Marino", slug: "sm", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "São Tomé & Príncipe", slug: "st", active: false, currencyCode: "STN", currencySymbol: "Db" },
  { name: "Saudi Arabia", slug: "sa", active: false, currencyCode: "SAR", currencySymbol: "ر.س" },
  { name: "Senegal", slug: "sn", active: false, currencyCode: "XOF", currencySymbol: "CFA" },
  { name: "Serbia", slug: "rs", active: false, currencyCode: "RSD", currencySymbol: "дин" },
  { name: "Seychelles", slug: "sc", active: false, currencyCode: "SCR", currencySymbol: "₨" },
  { name: "Sierra Leone", slug: "sl", active: false, currencyCode: "SLL", currencySymbol: "Le" },
  { name: "Singapore", slug: "sg", active: false, currencyCode: "SGD", currencySymbol: "$" },
  { name: "Sint Maarten", slug: "sx", active: false, currencyCode: "ANG", currencySymbol: "ƒ" },
  { name: "Slovakia", slug: "sk", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Slovenia", slug: "si", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Solomon Islands", slug: "sb", active: false, currencyCode: "SBD", currencySymbol: "$" },
  { name: "Somalia", slug: "so", active: false, currencyCode: "SOS", currencySymbol: "Sh" },
  { name: "South Africa", slug: "za", active: false, currencyCode: "ZAR", currencySymbol: "R" },
  { name: "South Georgia & South Sandwich Islands", slug: "gs", active: false, currencyCode: "GBP", currencySymbol: "£" },
  { name: "South Korea", slug: "kr", active: false, currencyCode: "KRW", currencySymbol: "₩" },
  { name: "South Sudan", slug: "ss", active: false, currencyCode: "SSP", currencySymbol: "£" },
  { name: "Spain", slug: "es", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Sri Lanka", slug: "lk", active: false, currencyCode: "LKR", currencySymbol: "₨" },
  { name: "St. Barthélemy", slug: "bl", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "St. Helena", slug: "sh", active: false, currencyCode: "SHP", currencySymbol: "£" },
  { name: "St. Kitts & Nevis", slug: "kn", active: false, currencyCode: "XCD", currencySymbol: "$" },
  { name: "St. Lucia", slug: "lc", active: false, currencyCode: "XCD", currencySymbol: "$" },
  { name: "St. Martin", slug: "mf", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "St. Pierre & Miquelon", slug: "pm", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "St. Vincent & Grenadines", slug: "vc", active: false, currencyCode: "XCD", currencySymbol: "$" },
  { name: "Sudan", slug: "sd", active: false, currencyCode: "SDG", currencySymbol: "ج.س." },
  { name: "Suriname", slug: "sr", active: false, currencyCode: "SRD", currencySymbol: "$" },
  { name: "Svalbard & Jan Mayen", slug: "sj", active: false, currencyCode: "NOK", currencySymbol: "kr" },
  { name: "Sweden", slug: "se", active: false, currencyCode: "SEK", currencySymbol: "kr" },
  { name: "Switzerland", slug: "ch", active: false, currencyCode: "CHF", currencySymbol: "CHF" },
  { name: "Syria", slug: "sy", active: false, currencyCode: "SYP", currencySymbol: "£" },
  { name: "Taiwan", slug: "tw", active: false, currencyCode: "TWD", currencySymbol: "NT$" },
  { name: "Tajikistan", slug: "tj", active: false, currencyCode: "TJS", currencySymbol: "SM" },
  { name: "Tanzania", slug: "tz", active: false, currencyCode: "TZS", currencySymbol: "TSh" },
  { name: "Thailand", slug: "th", active: false, currencyCode: "THB", currencySymbol: "฿" },
  { name: "Timor-Leste", slug: "tl", active: false, currencyCode: "USD", currencySymbol: "$" },
  { name: "Togo", slug: "tg", active: false, currencyCode: "XOF", currencySymbol: "CFA" },
  { name: "Tokelau", slug: "tk", active: false, currencyCode: "NZD", currencySymbol: "$" },
  { name: "Tonga", slug: "to", active: false, currencyCode: "TOP", currencySymbol: "T$" },
  { name: "Trinidad & Tobago", slug: "tt", active: false, currencyCode: "TTD", currencySymbol: "$" },
  { name: "Tristan da Cunha", slug: "ta", active: false, currencyCode: "GBP", currencySymbol: "£" },
  { name: "Tunisia", slug: "tn", active: false, currencyCode: "TND", currencySymbol: "د.ت" },
  { name: "Türkiye", slug: "tr", active: false, currencyCode: "TRY", currencySymbol: "₺" },
  { name: "Turkmenistan", slug: "tm", active: false, currencyCode: "TMT", currencySymbol: "m" },
  { name: "Turks & Caicos Islands", slug: "tc", active: false, currencyCode: "USD", currencySymbol: "$" },
  { name: "Tuvalu", slug: "tv", active: false, currencyCode: "AUD", currencySymbol: "$" },
  { name: "U.S. Outlying Islands", slug: "um", active: false, currencyCode: "USD", currencySymbol: "$" },
  { name: "Uganda", slug: "ug", active: false, currencyCode: "UGX", currencySymbol: "USh" },
  { name: "Ukraine", slug: "ua", active: false, currencyCode: "UAH", currencySymbol: "₴" },
  { name: "United Arab Emirates", slug: "ae", active: false, currencyCode: "AED", currencySymbol: "د.إ" },
  { name: "United Kingdom", slug: "gb", active: false, currencyCode: "GBP", currencySymbol: "£" },
  { name: "United States", slug: "us", active: false, currencyCode: "USD", currencySymbol: "$" },
  { name: "Unknown Region", slug: "zz", active: false, currencyCode: "USD", currencySymbol: "$" },
  { name: "Uruguay", slug: "uy", active: false, currencyCode: "UYU", currencySymbol: "$" },
  { name: "Uzbekistan", slug: "uz", active: false, currencyCode: "UZS", currencySymbol: "soʻm" },
  { name: "Vanuatu", slug: "vu", active: false, currencyCode: "VUV", currencySymbol: "VT" },
  { name: "Vatican City", slug: "va", active: false, currencyCode: "EUR", currencySymbol: "€" },
  { name: "Venezuela", slug: "ve", active: false, currencyCode: "VES", currencySymbol: "Bs." },
  { name: "Vietnam", slug: "vn", active: false, currencyCode: "VND", currencySymbol: "₫" },
  { name: "Wallis & Futuna", slug: "wf", active: false, currencyCode: "XPF", currencySymbol: "₣" },
  { name: "Western Sahara", slug: "eh", active: false, currencyCode: "MAD", currencySymbol: "د.م." },
  { name: "Yemen", slug: "ye", active: false, currencyCode: "YER", currencySymbol: "ر.ي" },
  { name: "Zambia", slug: "zm", active: false, currencyCode: "ZMW", currencySymbol: "ZK" },
  { name: "Zimbabwe", slug: "zw", active: false, currencyCode: "ZWL", currencySymbol: "$" }, */
];

export function getCurrencySymbol(currencyCode: string): string {
  const country = countries.find((c) => c.currencyCode === currencyCode);
  return country?.currencySymbol || currencyCode; // Fallback to code if symbol not found
}

export interface Banner {
  image: string;
  headline: string;
  subtitle: string;
}

export type Banners = {
  [key: string]: Banner[];
};

export const banners: Banners = {
  in: [
    {
      image: "/banners/CountryHeroBanners/in-hero-banner.webp",
      headline: "lugdi",
      subtitle: "Heritage in Every Thread, Luxury in Every Detail",
    },
  ],
};
