export interface Country {
  name: string;
  slug: string;
  active: boolean;
}

export const countries: Country[] = [
  { name: "India", slug: "in", active: true },
  { name: "Australia", slug: "au", active: true },

  /* { name: "Afghanistan", slug: "af", active: false },
  { name: "Åland Islands", slug: "ax", active: false },
  { name: "Albania", slug: "al", active: false },
  { name: "Algeria", slug: "dz", active: false },
  { name: "Andorra", slug: "ad", active: false },
  { name: "Angola", slug: "ao", active: false },
  { name: "Anguilla", slug: "ai", active: false },
  { name: "Antigua & Barbuda", slug: "ag", active: false },
  { name: "Argentina", slug: "ar", active: false },
  { name: "Armenia", slug: "am", active: false },
  { name: "Aruba", slug: "aw", active: false },
  { name: "Ascension Island", slug: "ac", active: false },
  
  { name: "Austria", slug: "at", active: false },
  { name: "Azerbaijan", slug: "az", active: false },
  { name: "Bahamas", slug: "bs", active: false },
  { name: "Bahrain", slug: "bh", active: false },
  { name: "Bangladesh", slug: "bd", active: false },
  { name: "Barbados", slug: "bb", active: false },
  { name: "Belarus", slug: "by", active: false },
  { name: "Belgium", slug: "be", active: false },
  { name: "Belize", slug: "bz", active: false },
  { name: "Benin", slug: "bj", active: false },
  { name: "Bermuda", slug: "bm", active: false },
  { name: "Bhutan", slug: "bt", active: false },
  { name: "Bolivia", slug: "bo", active: false },
  { name: "Bosnia & Herzegovina", slug: "ba", active: false },
  { name: "Botswana", slug: "bw", active: false },
  { name: "Bouvet Island", slug: "bv", active: false },
  { name: "Brazil", slug: "br", active: false },
  { name: "British Indian Ocean Territory", slug: "io", active: false },
  { name: "British Virgin Islands", slug: "vg", active: false },
  { name: "Brunei", slug: "bn", active: false },
  { name: "Bulgaria", slug: "bg", active: false },
  { name: "Burkina Faso", slug: "bf", active: false },
  { name: "Burundi", slug: "bi", active: false },
  { name: "Cambodia", slug: "kh", active: false },
  { name: "Cameroon", slug: "cm", active: false },
  { name: "Canada", slug: "ca", active: false },
  { name: "Cape Verde", slug: "cv", active: false },
  { name: "Caribbean Netherlands", slug: "bq", active: false },
  { name: "Cayman Islands", slug: "ky", active: false },
  { name: "Central African Republic", slug: "cf", active: false },
  { name: "Chad", slug: "td", active: false },
  { name: "Chile", slug: "cl", active: false },
  { name: "China", slug: "cn", active: false },
  { name: "Christmas Island", slug: "cx", active: false },
  { name: "Cocos (Keeling) Islands", slug: "cc", active: false },
  { name: "Colombia", slug: "co", active: false },
  { name: "Comoros", slug: "km", active: false },
  { name: "Congo - Brazzaville", slug: "cg", active: false },
  { name: "Congo - Kinshasa", slug: "cd", active: false },
  { name: "Cook Islands", slug: "ck", active: false },
  { name: "Costa Rica", slug: "cr", active: false },
  { name: "Côte d’Ivoire", slug: "ci", active: false },
  { name: "Croatia", slug: "hr", active: false },
  { name: "Cuba", slug: "cu", active: false },
  { name: "Curaçao", slug: "cw", active: false },
  { name: "Cyprus", slug: "cy", active: false },
  { name: "Czechia", slug: "cz", active: false },
  { name: "Denmark", slug: "dk", active: false },
  { name: "Djibouti", slug: "dj", active: false },
  { name: "Dominica", slug: "dm", active: false },
  { name: "Dominican Republic", slug: "do", active: false },
  { name: "Ecuador", slug: "ec", active: false },
  { name: "Egypt", slug: "eg", active: false },
  { name: "El Salvador", slug: "sv", active: false },
  { name: "Equatorial Guinea", slug: "gq", active: false },
  { name: "Eritrea", slug: "er", active: false },
  { name: "Estonia", slug: "ee", active: false },
  { name: "Eswatini", slug: "sz", active: false },
  { name: "Ethiopia", slug: "et", active: false },
  { name: "Falkland Islands", slug: "fk", active: false },
  { name: "Faroe Islands", slug: "fo", active: false },
  { name: "Fiji", slug: "fj", active: false },
  { name: "Finland", slug: "fi", active: false },
  { name: "France", slug: "fr", active: false },
  { name: "French Guiana", slug: "gf", active: false },
  { name: "French Polynesia", slug: "pf", active: false },
  { name: "French Southern Territories", slug: "tf", active: false },
  { name: "Gabon", slug: "ga", active: false },
  { name: "Gambia", slug: "gm", active: false },
  { name: "Georgia", slug: "ge", active: false },
  { name: "Germany", slug: "de", active: false },
  { name: "Ghana", slug: "gh", active: false },
  { name: "Gibraltar", slug: "gi", active: false },
  { name: "Greece", slug: "gr", active: false },
  { name: "Greenland", slug: "gl", active: false },
  { name: "Grenada", slug: "gd", active: false },
  { name: "Guadeloupe", slug: "gp", active: false },
  { name: "Guatemala", slug: "gt", active: false },
  { name: "Guernsey", slug: "gg", active: false },
  { name: "Guinea", slug: "gn", active: false },
  { name: "Guinea-Bissau", slug: "gw", active: false },
  { name: "Guyana", slug: "gy", active: false },
  { name: "Haiti", slug: "ht", active: false },
  { name: "Heard & McDonald Islands", slug: "hm", active: false },
  { name: "Honduras", slug: "hn", active: false },
  { name: "Hong Kong SAR", slug: "hk", active: false },
  { name: "Hungary", slug: "hu", active: false },
  { name: "Iceland", slug: "is", active: false },
  { name: "Indonesia", slug: "id", active: false },
  { name: "Iran", slug: "ir", active: false },
  { name: "Iraq", slug: "iq", active: false },
  { name: "Ireland", slug: "ie", active: false },
  { name: "Isle of Man", slug: "im", active: false },
  { name: "Israel", slug: "il", active: false },
  { name: "Italy", slug: "it", active: false },
  { name: "Jamaica", slug: "jm", active: false },
  { name: "Japan", slug: "jp", active: false },
  { name: "Jersey", slug: "je", active: false },
  { name: "Jordan", slug: "jo", active: false },
  { name: "Kazakhstan", slug: "kz", active: false },
  { name: "Kenya", slug: "ke", active: false },
  { name: "Kiribati", slug: "ki", active: false },
  { name: "Kosovo", slug: "xk", active: false },
  { name: "Kuwait", slug: "kw", active: false },
  { name: "Kyrgyzstan", slug: "kg", active: false },
  { name: "Laos", slug: "la", active: false },
  { name: "Latvia", slug: "lv", active: false },
  { name: "Lebanon", slug: "lb", active: false },
  { name: "Lesotho", slug: "ls", active: false },
  { name: "Liberia", slug: "lr", active: false },
  { name: "Libya", slug: "ly", active: false },
  { name: "Liechtenstein", slug: "li", active: false },
  { name: "Lithuania", slug: "lt", active: false },
  { name: "Luxembourg", slug: "lu", active: false },
  { name: "Macao SAR", slug: "mo", active: false },
  { name: "Madagascar", slug: "mg", active: false },
  { name: "Malawi", slug: "mw", active: false },
  { name: "Malaysia", slug: "my", active: false },
  { name: "Maldives", slug: "mv", active: false },
  { name: "Mali", slug: "ml", active: false },
  { name: "Malta", slug: "mt", active: false },
  { name: "Martinique", slug: "mq", active: false },
  { name: "Mauritania", slug: "mr", active: false },
  { name: "Mauritius", slug: "mu", active: false },
  { name: "Mayotte", slug: "yt", active: false },
  { name: "Mexico", slug: "mx", active: false },
  { name: "Moldova", slug: "md", active: false },
  { name: "Monaco", slug: "mc", active: false },
  { name: "Mongolia", slug: "mn", active: false },
  { name: "Montenegro", slug: "me", active: false },
  { name: "Montserrat", slug: "ms", active: false },
  { name: "Morocco", slug: "ma", active: false },
  { name: "Mozambique", slug: "mz", active: false },
  { name: "Myanmar (Burma)", slug: "mm", active: false },
  { name: "Namibia", slug: "na", active: false },
  { name: "Nauru", slug: "nr", active: false },
  { name: "Nepal", slug: "np", active: false },
  { name: "Netherlands", slug: "nl", active: false },
  { name: "Netherlands Antilles", slug: "an", active: false },
  { name: "New Caledonia", slug: "nc", active: false },
  { name: "New Zealand", slug: "nz", active: false },
  { name: "Nicaragua", slug: "ni", active: false },
  { name: "Niger", slug: "ne", active: false },
  { name: "Nigeria", slug: "ng", active: false },
  { name: "Niue", slug: "nu", active: false },
  { name: "Norfolk Island", slug: "nf", active: false },
  { name: "North Korea", slug: "kp", active: false },
  { name: "North Macedonia", slug: "mk", active: false },
  { name: "Norway", slug: "no", active: false },
  { name: "Oman", slug: "om", active: false },
  { name: "Pakistan", slug: "pk", active: false },
  { name: "Palestinian Territories", slug: "ps", active: false },
  { name: "Panama", slug: "pa", active: false },
  { name: "Papua New Guinea", slug: "pg", active: false },
  { name: "Paraguay", slug: "py", active: false },
  { name: "Peru", slug: "pe", active: false },
  { name: "Philippines", slug: "ph", active: false },
  { name: "Pitcairn Islands", slug: "pn", active: false },
  { name: "Poland", slug: "pl", active: false },
  { name: "Portugal", slug: "pt", active: false },
  { name: "Qatar", slug: "qa", active: false },
  { name: "Réunion", slug: "re", active: false },
  { name: "Romania", slug: "ro", active: false },
  { name: "Russia", slug: "ru", active: false },
  { name: "Rwanda", slug: "rw", active: false },
  { name: "Samoa", slug: "ws", active: false },
  { name: "San Marino", slug: "sm", active: false },
  { name: "São Tomé & Príncipe", slug: "st", active: false },
  { name: "Saudi Arabia", slug: "sa", active: false },
  { name: "Senegal", slug: "sn", active: false },
  { name: "Serbia", slug: "rs", active: false },
  { name: "Seychelles", slug: "sc", active: false },
  { name: "Sierra Leone", slug: "sl", active: false },
  { name: "Singapore", slug: "sg", active: false },
  { name: "Sint Maarten", slug: "sx", active: false },
  { name: "Slovakia", slug: "sk", active: false },
  { name: "Slovenia", slug: "si", active: false },
  { name: "Solomon Islands", slug: "sb", active: false },
  { name: "Somalia", slug: "so", active: false },
  { name: "South Africa", slug: "za", active: false },
  { name: "South Georgia & South Sandwich Islands", slug: "gs", active: false },
  { name: "South Korea", slug: "kr", active: false },
  { name: "South Sudan", slug: "ss", active: false },
  { name: "Spain", slug: "es", active: false },
  { name: "Sri Lanka", slug: "lk", active: false },
  { name: "St. Barthélemy", slug: "bl", active: false },
  { name: "St. Helena", slug: "sh", active: false },
  { name: "St. Kitts & Nevis", slug: "kn", active: false },
  { name: "St. Lucia", slug: "lc", active: false },
  { name: "St. Martin", slug: "mf", active: false },
  { name: "St. Pierre & Miquelon", slug: "pm", active: false },
  { name: "St. Vincent & Grenadines", slug: "vc", active: false },
  { name: "Sudan", slug: "sd", active: false },
  { name: "Suriname", slug: "sr", active: false },
  { name: "Svalbard & Jan Mayen", slug: "sj", active: false },
  { name: "Sweden", slug: "se", active: false },
  { name: "Switzerland", slug: "ch", active: false },
  { name: "Syria", slug: "sy", active: false },
  { name: "Taiwan", slug: "tw", active: false },
  { name: "Tajikistan", slug: "tj", active: false },
  { name: "Tanzania", slug: "tz", active: false },
  { name: "Thailand", slug: "th", active: false },
  { name: "Timor-Leste", slug: "tl", active: false },
  { name: "Togo", slug: "tg", active: false },
  { name: "Tokelau", slug: "tk", active: false },
  { name: "Tonga", slug: "to", active: false },
  { name: "Trinidad & Tobago", slug: "tt", active: false },
  { name: "Tristan da Cunha", slug: "ta", active: false },
  { name: "Tunisia", slug: "tn", active: false },
  { name: "Türkiye", slug: "tr", active: false },
  { name: "Turkmenistan", slug: "tm", active: false },
  { name: "Turks & Caicos Islands", slug: "tc", active: false },
  { name: "Tuvalu", slug: "tv", active: false },
  { name: "U.S. Outlying Islands", slug: "um", active: false },
  { name: "Uganda", slug: "ug", active: false },
  { name: "Ukraine", slug: "ua", active: false },
  { name: "United Arab Emirates", slug: "ae", active: false },
  { name: "United Kingdom", slug: "gb", active: false },
  { name: "United States", slug: "us", active: false },
  { name: "Unknown Region", slug: "zz", active: false },
  { name: "Uruguay", slug: "uy", active: false },
  { name: "Uzbekistan", slug: "uz", active: false },
  { name: "Vanuatu", slug: "vu", active: false },
  { name: "Vatican City", slug: "va", active: false },
  { name: "Venezuela", slug: "ve", active: false },
  { name: "Vietnam", slug: "vn", active: false },
  { name: "Wallis & Futuna", slug: "wf", active: false },
  { name: "Western Sahara", slug: "eh", active: false },
  { name: "Yemen", slug: "ye", active: false },
  { name: "Zambia", slug: "zm", active: false },
  { name: "Zimbabwe", slug: "zw", active: false }, */
];

export interface Banner {
  image: string;
  headline: string;
  subtitle: string;
}

export type Banners = {
  [key: string]: Banner[];
};

export const banners: Banners = {
  in: [
    {
      image: "/banners/CountryHeroBanners/in-hero-banner.webp",
      headline: "lugdi",
      subtitle: "Heritage in Every Thread, Luxury in Every Detail",
    },
  ],
};
